Update checksums, versions and add nccl interface for cudensitymat.

diff --git a/recipe/cudensitymat/cudm-install b/recipe/cudensitymat/cudm-install
--- a/recipe/cudensitymat/cudm-install
+++ b/recipe/cudensitymat/cudm-install
@@ -44,6 +44,35 @@ conda clean --all --yes
       echo "error: cudensitymat comm lib not in expected place"
       exit 1
     fi
+    # build the nccl wrapper lib
+    if ! [[ -f "distributed_interfaces/cudensitymat_distributed_interface_nccl.c" ]] ; then
+      echo " error: nccl distributed interface source not found in expected location "
+      exit 1
+    fi
+    if ! [[ -f "${PREFIX}/include/nccl.h" ]] ; then
+      echo " error: nccl headers not found in ${PREFIX}/include "
+      exit 1
+    fi
+    if ! ls "${PREFIX}/lib/libnccl.so"* >/dev/null 2>&1 ; then
+      echo " error: nccl library not found in ${PREFIX}/lib "
+      exit 1
+    fi
+    declare -a nccl_compile_command
+    nccl_compile_command=(
+        "${NVCC:-"nvcc"}" "-shared" "-Xcompiler" "-fPIC" ${CFLAGS} "-I${PREFIX}/include"
+        "distributed_interfaces/cudensitymat_distributed_interface_nccl.c"
+        "-L${PREFIX}/lib" "-lnccl" "-lcudart"
+        "-o" "${PREFIX}/lib/libcudensitymat_distributed_interface_nccl.so"
+      )
+    echo "nccl_compile_command[@]"
+    "${nccl_compile_command[@]}"
+
+    check-glibc ${PREFIX}/lib/libcudensitymat_distributed_interface_nccl.so
+
+    if ! [[ -f "${PREFIX}/lib/libcudensitymat_distributed_interface_nccl.so" ]] ; then
+      echo "error: cudensitymat nccl comm lib not in expected place"
+      exit 1
+    fi
     # copy activate/deactivate scripts
     mkdir -p "${PREFIX}/etc/conda/activate.d"
     cp "${RECIPE_DIR}/cudensitymat/cudm-activate.sh" "${PREFIX}/etc/conda/activate.d/cudm-activate.sh" 
diff --git a/recipe/cudensitymat/cudm-tests b/recipe/cudensitymat/cudm-tests
--- a/recipe/cudensitymat/cudm-tests
+++ b/recipe/cudensitymat/cudm-tests
@@ -30,6 +30,11 @@ if [[ -f "${PREFIX}/lib/libmpi.so" ]] ; then
   LINK_MPI="-lmpi"
 fi
 
+declare -gx LINK_NCCL=""
+if ls "${PREFIX}/lib/libnccl.so"* >/dev/null 2>&1 ; then
+  LINK_NCCL="-lnccl"
+fi
+
 declare -gx CUQUANTUM_VER="${1}"
 if [[ -n "${CUQUANTUM_VER}" ]] ; then
   declare -agx CUQUANTUM_VERSION
@@ -47,18 +52,45 @@ if [[ -n "${CUQUANTUM_VER}" ]] ; then
     declare -a compile_command
     export LD_LIBRARY_PATH="${PREFIX}/lib"
     declare example ; for example in "${examples[@]}" ; do
-      if [[ "${example}" != *"mpi"* ]] ; then
+      if [[ "${example}" != *"mpi"* && "${example}" != *"nccl"* ]] ; then
         echo "${example}"
         compile_command=(
           "${NVCC:-"nvcc"}" "${NVCC_FLAGS:-"--verbose"}" "--std=c++17"
           "-I${PREFIX}/include" "-L${PREFIX}/lib"
           "-lcudensitymat" "-lcutensornet" "-lcutensor"
           "${example}" "-o" "${example}.out"
-        )  
+        )
         echo "${compile_command[@]}"
         "${compile_command[@]}"
       fi
     done
+
+    if [[ "${mpi}" != "nompi" ]] ; then
+      declare example ; for example in "${examples[@]}" ; do
+        if [[ "${example}" == *"mpi"* && "${example}" != *"nccl"* ]] ; then
+          echo "${example}"
+          compile_command=(
+            "${NVCC:-"nvcc"}" "${NVCC_FLAGS:-"--verbose"}" "--std=c++17"
+            "-I${PREFIX}/include" "-L${PREFIX}/lib"
+            "-lcudensitymat" "-lcutensornet" "-lcutensor" "${LINK_MPI}"
+            "${example}" "-o" "${example}.out"
+          )
+          echo "${compile_command[@]}"
+          "${compile_command[@]}"
+        fi
+        if [[ "${example}" == *"nccl"* ]] ; then
+          echo "${example}"
+          compile_command=(
+            "${NVCC:-"nvcc"}" "${NVCC_FLAGS:-"--verbose"}" "--std=c++17"
+            "-I${PREFIX}/include" "-L${PREFIX}/lib"
+            "-lcudensitymat" "-lcutensornet" "-lcutensor" "${LINK_NCCL}"
+            "${example}" "-o" "${example}.out"
+          )
+          echo "${compile_command[@]}"
+          "${compile_command[@]}"
+        fi
+      done
+    fi
   )}
 fi
 
@@ -66,6 +98,10 @@ fi
 if [[ "${mpi}" != "nompi" ]] ; then
   if ! [[ -f "${CUDENSITYMAT_COMM_LIB}" ]]; then
     echo "error: cudensitymat distributed interface not set in an MPI build"
+    exit 1
+  fi
+  if ! [[ -f "${PREFIX}/lib/libcudensitymat_distributed_interface_nccl.so" ]]; then
+    echo "error: cudensitymat nccl distributed interface not found in an MPI build"
     exit 1
   fi
 fi
