Add distributed interfaces builds and tests for MPI builds.

diff --git a/recipe/common/validate-glibc b/recipe/common/validate-glibc
--- a/recipe/common/validate-glibc
+++ b/recipe/common/validate-glibc
@@ -15,6 +15,20 @@
     exit 1
   fi
 
+  RECIPE_GLIBC="$(
+        glibc-detect env c_stdlib_version
+      )"
+      echo "Recipe-glibc: ${RECIPE_GLIBC}"
+  if [[ -z "${RECIPE_GLIBC}" ]] ; then
+    echo "error: recipe glibc not set"
+    exit 1
+  fi
+
+  SYSTEM_GLIBC="$(
+        glibc-detect system
+      )"
+      echo "System-glibc: ${SYSTEM_GLIBC}"  
+
   declare -agx LIBRARIES
   if [[ -z "${LIBRARIES[*]}" ]] ; then
     LIBRARIES=("${@}")
@@ -27,14 +41,6 @@
         glibc-detect required-by "${LIBRARY}"
       )"
       echo "Library-glibc: ${LIBRARY_GLIBC}"
-      RECIPE_GLIBC="$(
-        glibc-detect env c_stdlib_version
-      )"
-      echo "Recipe-glibc: ${RECIPE_GLIBC}"
-      SYSTEM_GLIBC="$(
-        glibc-detect system
-      )"
-      echo "System-glibc: ${SYSTEM_GLIBC}"
       glibc-check compatible "${SYSTEM_GLIBC}" "${RECIPE_GLIBC}" || {
         echo "warning: the glibc version required by the recipe"
         echo "         is not compatible with the system glibc version"
diff --git a/recipe/cutensornet/cutn-install b/recipe/cutensornet/cutn-install
--- a/recipe/cutensornet/cutn-install
+++ b/recipe/cutensornet/cutn-install
@@ -17,9 +17,53 @@ conda clean --all --yes
   declare -gx from named
   from="include" named="*cutensornet.h*" files move "${PREFIX}/include"
   from="include/cutensornet" named="*.h*" files move "${PREFIX}/include/cutensornet"
-  
   from="lib" named="*cutensornet.so*" files move "${PREFIX}/lib"
+  
+  if [[ "${mpi}" != "nompi" ]]; then
+  #if [[ -f "${PREFIX}/lib/libmpi.so" ]] ; then
+    echo " detected mpi lib, building wrappers" 
+    # build the mpi wrapper lib  
+    if ! [[ -f "distributed_interfaces/cutensornet_distributed_interface_mpi.c" ]] ; then
+      echo " error: distributed interface source not found in expected location "
+      exit 1
+    fi
+    declare -a compile_command
+    if [[ "${cuda_compiler_version}" == "11.8" ]]; then
+      compile_command=(
+          "${GCC}" "-shared" "-std=c11" "-fPIC"
+          "-I${CUDA_PATH}/include" "-I${PREFIX}/include"
+          "distributed_interfaces/cutensornet_distributed_interface_mpi.c"
+          "-L${PREFIX}/lib" "-lmpi"
+          "-o" "${PREFIX}/lib/libcutensornet_distributed_interface_mpi.so"
+        )
+      #"${GCC}" "-shared" "-std=c11" "-fPIC" "-I${CUDA_PATH}/include" "-I${PREFIX}/include" "distributed_interfaces/cutensornet_distributed_interface_mpi.c" "-L${PREFIX}/lib" "-lmpi" "-o" "${PREFIX}/lib/libcutensornet_distributed_interface_mpi.so"
+    elif [[ "${cuda_compiler_version}" == "12.0" ]] ||  [[ "${cuda_compiler_version}" == "12.6" ]]; then
+      compile_command=(
+          "${GCC}" "-shared" "-std=c11" "-fPIC" ${CFLAGS} "-I${PREFIX}/include"
+          "distributed_interfaces/cutensornet_distributed_interface_mpi.c"
+          "-L${PREFIX}/lib" "-lmpi"
+          "-o" "${PREFIX}/lib/libcutensornet_distributed_interface_mpi.so"
+        )
+      #"${GCC}" "-shared" "-std=c11" "-fPIC" ${CFLAGS} "-I${PREFIX}/include" "distributed_interfaces/cutensornet_distributed_interface_mpi.c" "-L${PREFIX}/lib" "-lmpi" "-o" "${PREFIX}/lib/libcutensornet_distributed_interface_mpi.so"
+    else
+      echo "error: incompatible cuda version"
+      exit 1
+    fi
+    echo "compile_command[@]"
+    "${compile_command[@]}"
+    if ! [[ -f "${PREFIX}/lib/libcutensornet_distributed_interface_mpi.so" ]] ; then
+      echo "error: cutensornet comm lib not in expected place, exiting"
+      exit 1
+    fi
+    # copy activate/deactivate scripts
+    mkdir -p "${PREFIX}/etc/conda/activate.d"
+    cp "${RECIPE_DIR}/cutensornet/cutn-activate.sh" "${PREFIX}/etc/conda/activate.d/cutn-activate.sh" 
+    mkdir -p "${PREFIX}/etc/conda/deactivate.d"
+    cp "${RECIPE_DIR}/cutensornet/cutn-deactivate.sh" "${PREFIX}/etc/conda/deactivate.d/cutn-deactivate.sh"
+  else
+    echo " not detected mpi lib, not building wrappers"
+  fi
+  
 )}
-
 
 
diff --git a/recipe/cutensornet/cutn-tests b/recipe/cutensornet/cutn-tests
--- a/recipe/cutensornet/cutn-tests
+++ b/recipe/cutensornet/cutn-tests
@@ -92,3 +92,12 @@ if [[ -n "${CUQUANTUM_VER}" ]] ; then
     done
   )}
 fi
+
+# check for existence of distributed interface library if this is an MPI build
+if [[ "${mpi}" != "nompi" ]] ; then
+#if [[ -f "${PREFIX}/lib/libmpi.so" ]] ; then
+  if ! [[ -f "${CUTENSORNET_COMM_LIB}" ]]; then
+    echo "error: cutensornet distributed interface not set in an MPI build"
+    exit 1
+  fi
+fi
